### ISSUE TITLE
salesforceFunctions constructor anomaly

### ISSUE THREAD

**Issue by hnpilot** [Kephson/php-salesforce-rest-api#3]
I have tested this library and it works well but there's a strange anomaly.

The constructor is written so that $apiVersion is the first parameter but if I follow the documentation, instanceURL and accessToken should be enough in the constructor (and furthermore default value of apiVersion would be never used if I need to set either instanceUrl or accessToken which in my knowledge need to hapeen always).

I have bypassed the problem by moving the $apiversion parameter as the last parameter in the SalesforceFunctions constructor and after that everything is fine.

**Comment by Kephson** [comment]
thanks for reporting that, I released a new version 1.0.6
