### ISSUE TITLE
[FEATURE] Support for Salesforce REST API headers?

### ISSUE THREAD

**Issue by hvilminko** [Kephson/php-salesforce-rest-api#4]
## Summary / Description

In some cases we need to set HTTP headers on the REST API call to activate or disable some Salesforce features such as assignment rules or query options. See the header documentation in the SF REST API Developer Guide: [REST API Headers](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/headers.htm)

## Describe the solution you'd like

The most straightforward way to use headers would be to have a method on the SalesforceFunctions object to set the desired headers (in addition to the standard ones like Authorization) before doing the actual API call.

**Comment by Kephson** [comment]
Hi, I will check this and try to find a solution to include this feature.

**Comment by Kephson** [comment]
Hi @hvilminko I had to postpone this feature until the end of the year.
If you need this feature faster feel free to provide a pull request.

**Comment by Kephson** [comment]
closed with ff1c6a8f04569edc56c8d837169d796f7c508834 and the new released version 1.1.0 on packagist
