### ISSUE TITLE
[FEATURE] List alternative packages in the documentation

### ISSUE THREAD

**Issue by rodrigoaguilera** [Kephson/php-salesforce-rest-api#5]
## Summary 

I was very happy to find this library on packagist to develop a salesforce integration but digging deeper I found a Doctrine DBAL that has a similar purpose
https://github.com/codelicia/trineforce

It fits more my project needs and I don't have to worry about sanitizing the parameters for the queries since that is done by doctrine.

I also discovered an eloquent model for salesforce
https://github.com/roblesterjr04/EloquentSalesForce
but I don't want to use laravel for this particular project.

## Describe the solution you'd like

My main goal is to make people aware of the alternatives so even if only the maintainer reads this issue is fine but I think it can be beneficial to have a little section in the readme that lists alternatives. I will propose the same on the other packages.

**Comment by Kephson** [comment]
Thanks a lot, I updated the readme file with some information about this libraries.
