### ISSUE TITLE
Upsert response code 200

### ISSUE THREAD

**Issue by iammartinbelobrad** [Kephson/php-salesforce-rest-api#6]
`EHAERER\Salesforce\Exception\SalesforceException: Error: call to URL https://xxxxxxxxxxxx.sandbox.my.salesforce.com/services/data/v57.0/sobjects/Account/Id/001AW00000DVwmbYAD failed with status 200, response: OK in /var/www/db3/temify/vendor/ehaerer/php-salesforce-rest-api/src/SalesforceFunctions.php:319`

**Comment by Kephson** [comment]
Hi, I closed this issue with the latest release of this package. Updated the response code check to latest API version of Salesforce: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/errorcodes.htm

**Comment by iammartinbelobrad** [comment]
You fixed in wrong way. You must use AND, not OR. This not work.

Error: call to URL https://xxxxxxxxxx.sandbox.my.salesforce.com/services/data/v57.0/sobjects/Account/z_PRIMARY_KEY__c/101000000000016 failed with status 200, response: OK

**Comment by Kephson** [comment]
Sorry, had an error in thought... now it should work with the new version.
